### ISSUE TITLE
在Ubuntu启动BOT报错

### ISSUE THREAD

**Issue by ElaineOwO** [Cvandia/nonebot-plugin-whateat-pic#11]
04-17 19:21:39 [ERROR] nonebot | Failed to import "nonebot_plugin_whateat_pic"
Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/home/elaine/.cache/activestate/1e8d7fa3/usr/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/home/elaine/.cache/activestate/1e8d7fa3/usr/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/home/elaine/.cache/activestate/1e8d7fa3/usr/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/home/elaine/.cache/activestate/1e8d7fa3/usr/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/home/elaine/.cache/activestate/1e8d7fa3/usr/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/home/elaine/.cache/activestate/1e8d7fa3/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/home/elaine/.cache/activestate/1e8d7fa3/usr/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/elaine/.cache/activestate/1e8d7fa3/usr/lib/python3.10/site-packages/nonebot_plugin_whateat_pic/__init__.py", line 22, in <module>
    import requests
  File "/home/elaine/.local/lib/python3.10/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
ModuleNotFoundError: No module named 'urllib3'

请大大帮帮看看这个叫urllib3的东西是怎么辉石qwq

**Comment by MomentQYC** [comment]
> 请大大帮帮看看这个叫urllib3的东西是怎么辉石qwq

`pip install urllib3`
