### ISSUE TITLE
添加菜单无反应，使用“查看全部菜单”时报错

### ISSUE THREAD

**Issue by KiriSuoh** [Cvandia/nonebot-plugin-whateat-pic#13]
我是小白不懂弄，看到作者大佬最近在更新了，但加qq还没回应，在这报一下

环境：win10x64 + LLonebot3.27.2 + nonebot2

发送指令“添加菜单”没有响应，加菜单名和图片也没有（我修改了配置项所以不需要开头的/）
```
07-22 16:52:11 [SUCCESS] nonebot | OneBot V11 2040209149 | [message.group.normal]: Message -2147481077 from 1925477085@[群:690623209] '添加菜单'
07-22 16:54:34 [SUCCESS] nonebot | OneBot V11 2040209149 | [message.group.normal]: Message -2147481076 from 1925477085@[群:690623209] '添加饮品 '
07-22 16:55:02 [SUCCESS] nonebot | OneBot V11 2040209149 | [message.group.normal]: Message -2147481075 from 1925477085@[群:690623209] '添加饮料'
07-22 16:56:46 [SUCCESS] nonebot | OneBot V11 2040209149 | [message.group.normal]: Message -2147481074 from 1925477085@[群:690623209] '添加菜单 法环小零食 [image:file=C7EAF474A76E3EC420C9D144FE6F8125.png,subType=0,url=https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoxOTI1...,file_size=640683]'
```

查看全部菜单的图片素材确实下载到了插件文件夹下，但发出要等很久，而且在调用send_forward_msg时报一串

```
07-22 16:34:41 [SUCCESS] nonebot | OneBot V11 2040209149 | [message.group.normal]: Message -2147481154 from 1925477085@[群:690623209] '查看全部菜单'
07-22 16:34:41 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_whateat_pic, lineno=77)
07-22 16:35:11 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_whateat_pic, lineno=77) running complete
07-22 16:35:11 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_whateat_pic, lineno=77) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Cyber\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Cyber\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Cyber\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Cyber\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Cyber\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Cyber\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
>File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot_plugin_whateat_pic\__init__.py", line 224, in handle
    await send_forward_msg(bot, event, Bot_NICKNAME, bot.self_id, msg_list)
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot_plugin_whateat_pic\__init__.py", line 334, in send_forward_msg
    return await bot.call_api(
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "F:\nonebot\FF_nb\.venv\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 149, in _call_api
    raise NetworkError(f"WebSocket call api {api} timeout") from None
nonebot.adapters.onebot.v11.exception.NetworkError: NetWorkError(message='WebSocket call api send_group_forward_msg timeout')
```

**Comment by Cvandia** [comment]
请问你使用的哪个`onebotv11`实现端

**Comment by KiriSuoh** [comment]
> 请问你使用的哪个`onebotv11`实现端

你好，我用的是LLOB https://github.com/LLOneBot/LLOneBot
在gocq不太行之后大家很多都换这个或者占用低的napcat了

**Comment by KiriSuoh** [comment]
已解决，添加菜单用超管能添加
